title : Jang Han's Blog for TIL
name: 'Jang Han's Blog for TIL'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  news:
    title: News
    default_open: false
    output: true
  posts:
    title: Today-I-Learned
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Today-I-Learned
      permalink: /post/:title
  - scope:
      type: News
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
